# Generated by Django 4.0.6 on 2022-08-09 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customuser_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=24)),
                ('city', models.CharField(max_length=24)),
                ('state', models.CharField(max_length=24)),
                ('country', models.CharField(max_length=24)),
                ('pincode', models.IntegerField()),
                ('locality', models.CharField(max_length=64)),
                ('landmark', models.CharField(max_length=64, null=True)),
                ('address', models.TextField()),
                ('alternate_number', models.BigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
