# Generated by Django 4.0.6 on 2022-08-09 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_useraddress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={'ordering': ['-id']},
        ),
    ]
