# Generated by Django 4.0.6 on 2022-08-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_fundaccout_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundaccout',
            name='account_number',
            field=models.PositiveBigIntegerField(),
        ),
    ]
