# Generated by Django 4.0.5 on 2022-06-21 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recentview',
            table=None,
        ),
    ]
