# Generated by Django 4.0.6 on 2022-07-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=64)),
                ('message', models.TextField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Contact us',
                'db_table': 'contact_us',
                'ordering': ['-created_at'],
            },
        ),
    ]
