# Generated by Django 3.2 on 2022-06-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_image_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_or_video', models.FileField(upload_to='banner')),
                ('caption', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'banners',
            },
        ),
    ]
