# Generated by Django 4.0.5 on 2022-06-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_recentview'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentview',
            name='views_counter',
            field=models.IntegerField(default=1),
        ),
    ]
