# Generated by Django 4.0.5 on 2022-06-21 08:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0002_alter_recentview_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecentView',
            new_name='RecentViewProduct',
        ),
        migrations.AlterModelTable(
            name='recentviewproduct',
            table='RecentViewProducts',
        ),
    ]
