# Generated by Django 3.2 on 2022-06-20 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_banner_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
