# Generated by Django 3.2 on 2022-05-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('couponCode', models.CharField(max_length=64)),
                ('percentageFlate', models.BooleanField(default=True)),
                ('discountValue', models.CharField(max_length=64)),
                ('maximumDiscountValue', models.IntegerField()),
                ('couponApplyCount', models.IntegerField()),
                ('maxApplyCount', models.IntegerField()),
                ('maxApplyCountPerUser', models.IntegerField()),
                ('startDateTime', models.DateTimeField()),
                ('expiryDateTime', models.DateTimeField()),
                ('min_value', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
