# Generated by Django 3.2 on 2022-05-24 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='min_value',
            new_name='minValue',
        ),
    ]
