# Generated by Django 4.0.6 on 2022-07-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='couponApplyCount',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='maxApplyCount',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='maxApplyCountPerUser',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='maximumDiscountValue',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='minValue',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
