# Generated by Django 3.2 on 2022-05-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_rename_min_value_coupon_minvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='couponApplyCount',
            field=models.IntegerField(default=0),
        ),
    ]
