# Generated by Django 3.2 on 2022-05-25 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_alter_coupon_couponapplycount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='maxApplyCountPerUser',
        ),
    ]
