# Generated by Django 3.2 on 2022-05-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0004_remove_coupon_maxapplycountperuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='maxApplyCountPerUser',
            field=models.IntegerField(default=1),
        ),
    ]
