# Generated by Django 3.2 on 2022-06-01 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0003_auto_20220525_1701'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('razorpay_payment_id', models.CharField(max_length=64)),
                ('razorpay_order_id', models.CharField(max_length=64)),
                ('razorpay_signature', models.CharField(max_length=64)),
                ('method', models.CharField(max_length=64)),
                ('fee', models.CharField(max_length=64)),
                ('tax', models.CharField(max_length=64)),
                ('error_code', models.TextField(blank=True, max_length=64, null=True)),
                ('error_description', models.TextField(blank=True, max_length=64, null=True)),
                ('error_source', models.TextField(blank=True, max_length=64, null=True)),
                ('error_step', models.TextField(blank=True, max_length=64, null=True)),
                ('error_reason', models.CharField(blank=True, max_length=64, null=True)),
                ('error_order_id', models.TextField(blank=True, max_length=64, null=True)),
                ('error_payment_id', models.TextField(blank=True, max_length=64, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='order.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Payments',
            },
        ),
    ]
