# Generated by Django 4.0.6 on 2022-08-20 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_requestrefundbankinfo_user'),
        ('rating_review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='order.orderitem'),
        ),
    ]
