# Generated by Django 3.2 on 2022-05-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20220511_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_item',
            field=models.IntegerField(default=0),
        ),
    ]
