# Generated by Django 3.2 on 2022-05-13 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20220513_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_total_price',
        ),
    ]
