# Generated by Django 4.0.6 on 2022-07-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page',
            field=models.CharField(choices=[('Home', 'Home'), ('About', 'About'), ('Contact', 'Contact'), ('shop', 'shop')], default='Home', max_length=64),
        ),
    ]
