# Generated by Django 4.0.6 on 2022-08-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0003_alter_page_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='is_cleaned',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
