# Generated by Django 4.0.6 on 2022-08-10 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0004_banner_is_cleaned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='is_cleaned',
        ),
    ]
