# Generated by Django 4.0.6 on 2022-08-10 14:00

import banner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0005_remove_banner_is_cleaned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image_or_video',
            field=models.FileField(upload_to='banner', validators=[banner.models.validate_image]),
        ),
    ]
