# Generated by Django 3.2 on 2022-05-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out For Shipping', 'Out For Shiping'), ('Completed', 'Completed'), ('Packed', 'Packed'), ('Cancel', 'Cancel')], default='Pendding', max_length=64),
        ),
    ]
