# Generated by Django 4.0.6 on 2022-07-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('order_cancelled', 'order cancelled'), ('order_pending', 'order pending'), ('order_success', 'order success'), ('partial_order_in_progress', 'partial order in progress'), ('partial_order', 'partial_order')], default='order_pending', max_length=64),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('payment_failed', 'payment failed'), ('payment_success', 'payment success'), ('payment_pending', 'payment pending'), ('partial_payment_refund_in_progress', 'Partial Payment Refund In Progress'), ('payment_refund_full', 'Payment Refund Full'), ('payment_refund_partial', 'Payment Refund Partial')], default='payment_pending', max_length=64),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out For Shipping', 'Out For Shiping'), ('Completed', 'Completed'), ('Packed', 'Packed'), ('Cancel', 'Cancel'), ('Delivered', 'Delivered'), ('refund_in_progress', 'Refund In Progress'), ('Refund', 'Refund')], default='Pendding', max_length=64),
        ),
    ]
