# Generated by Django 3.2 on 2022-05-25 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0004_remove_coupon_maxapplycountperuser'),
        ('order', '0002_auto_20220519_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='coupon.coupon'),
        ),
        migrations.AddField(
            model_name='order',
            name='discounted_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount_payble',
            field=models.FloatField(default=0),
        ),
    ]
