# Generated by Django 4.0.6 on 2022-07-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_order_status_alter_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('order_cancelled', 'order cancelled'), ('order_pending', 'order pending'), ('order_success', 'order success'), ('partial_order_in_progress', 'partial order in progress'), ('partial_order', 'partial_order'), ('partial_refund_failed', 'partial refund failed')], default='order_pending', max_length=64),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out For Shipping', 'Out For Shiping'), ('Completed', 'Completed'), ('Packed', 'Packed'), ('Cancel', 'Cancel'), ('Delivered', 'Delivered'), ('refund_in_progress', 'Refund In Progress'), ('Refund', 'Refund'), ('refund_failed', 'Refund Failed')], default='Pendding', max_length=64),
        ),
    ]
