# Generated by Django 3.2 on 2022-06-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20220525_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_due',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='amount_paid',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='attempts',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_status',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
