# Generated by Django 4.0.6 on 2022-07-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_order_status_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='alternate_number',
            field=models.BigIntegerField(),
        ),
    ]
