# Generated by Django 4.0.6 on 2022-08-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_alternate_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out For Shipping', 'Out For Shiping'), ('Completed', 'Completed'), ('Packed', 'Packed'), ('Cancel', 'Cancel'), ('Delivered', 'Delivered'), ('refund_in_progress', 'Refund In Progress'), ('Refund', 'Refund'), ('refund_failed', 'Refund Failed')], default='Pending', max_length=64),
        ),
    ]
