# Generated by Django 3.2 on 2022-06-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20220601_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('order_cancelled', 'order cancelled'), ('order_pending', 'order pending'), ('order_success', 'order success')], default='order_pending', max_length=16),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('payment_failed', 'payment failed'), ('payment_success', 'payment success'), ('payment_pending', 'payment pending')], default='payment_pending', max_length=16),
        ),
    ]
