# Generated by Django 4.0.6 on 2022-08-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('order cancelled', 'order cancelled'), ('order pending', 'order pending'), ('order success', 'order success'), ('partial order in progress', 'partial order in progress'), ('partial order', 'partial order'), ('partial refund failed', 'partial refund failed')], default='order_pending', max_length=64),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('payment_failed', 'payment failed'), ('payment_success', 'payment success'), ('payment_pending', 'payment pending'), ('Partial Payment Refund In Progress', 'Partial Payment Refund In Progress'), ('payment_refund_full', 'Payment Refund Full'), ('payment_refund_partial', 'Payment Refund Partial')], default='payment_pending', max_length=64),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out For Shipping', 'Out For Shiping'), ('Completed', 'Completed'), ('Packed', 'Packed'), ('Cancel', 'Cancel'), ('Delivered', 'Delivered'), ('Refund In Progress', 'Refund In Progress'), ('Refund', 'Refund'), ('Refund Failed', 'Refund Failed')], default='Pending', max_length=64),
        ),
    ]
