# Generated by Django 4.0.6 on 2022-08-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_order_status_alter_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('order cancelled', 'order cancelled'), ('order pending', 'order pending'), ('order success', 'order success'), ('partial order in progress', 'partial order in progress'), ('partial order', 'partial order'), ('partial refund failed', 'partial refund failed')], default='order pending', max_length=64),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('payment failed', 'payment failed'), ('payment success', 'payment success'), ('payment pending', 'payment pending'), ('Partial Payment Refund In Progress', 'Partial Payment Refund In Progress'), ('Payment Refund Full', 'Payment Refund Full'), ('Payment Refund Partial', 'Payment Refund Partial')], default='payment pending', max_length=64),
        ),
    ]
