# Generated by Django 4.0.6 on 2022-08-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_order_status_alter_order_payment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out For Shipping', 'Out For Shipping'), ('Completed', 'Completed'), ('Packed', 'Packed'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered'), ('Refund In Progress', 'Refund In Progress'), ('Refunded', 'Refunded'), ('Refund Failed', 'Refund Failed')], default='Pending', max_length=64),
        ),
    ]
