# Generated by Django 4.0.6 on 2022-08-09 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_useraddress_options'),
        ('order', '0009_remove_order_address_remove_order_alternate_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.useraddress'),
        ),
    ]
