# Generated by Django 4.0.6 on 2022-08-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_rename_shipping_address_order_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='request_refund',
            field=models.BooleanField(default=False),
        ),
    ]
