# Generated by Django 4.0.6 on 2022-08-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_orderitem_request_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out For Shipping', 'Out For Shipping'), ('Completed', 'Completed'), ('Packed', 'Packed'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered'), ('Refund In Progress', 'Refund In Progress'), ('Refunded', 'Refunded'), ('Refund Failed', 'Refund Failed'), ('Request Refund', 'Request Refund')], default='Pending', max_length=64),
        ),
    ]
