# Generated by Django 4.0.6 on 2022-08-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_orderitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='request_refund',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='make_refund',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
