# Generated by Django 4.0.6 on 2022-08-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_remove_orderitem_request_refund_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestRefundBankInfo',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ifsc_code', models.CharField(max_length=64)),
                ('account_number', models.PositiveBigIntegerField()),
                ('confirm_account_number', models.PositiveBigIntegerField()),
                ('account_holder_name', models.CharField(max_length=64)),
                ('phone_number', models.PositiveBigIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='make_refund',
        ),
    ]
