# Generated by Django 4.0.6 on 2022-08-12 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_requestrefundbankinfo_remove_orderitem_make_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestrefundbankinfo',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RequestRefundBankInfo', to='order.orderitem'),
        ),
    ]
