# Generated by Django 4.0.6 on 2022-08-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_requestrefundbankinfo_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRefundPolicy',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('return_refund_timestamp', models.CharField(choices=[('7 days', '7 days'), ('14 days', '14 days'), ('30 days', '30 days'), ('45 days', '45 days')], default='7 days', max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
