# Generated by Django 4.0.6 on 2022-08-13 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_old_price_alter_product_price_and_more'),
        ('order', '0018_returnrefundpolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiveReturn',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_return', to='order.order')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_return', to='order.orderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_return', to='store.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
