# Generated by Django 4.0.6 on 2022-08-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_receivereturn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receivereturn',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Receive Return'},
        ),
        migrations.AlterModelOptions(
            name='returnrefundpolicy',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Return Refund Policy'},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_return',
            field=models.BooleanField(default=False),
        ),
    ]
