# Generated by Django 4.0.6 on 2022-08-13 10:31

from django.db import migrations, models
import django.db.models.deletion
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_requestrefundbankinfo_is_refunded'),
    ]

   