# Generated by Django 4.0.6 on 2022-08-18 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0023_requestrefundbankinfo_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestrefundbankinfo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RequestRefundBankInfo', to=settings.AUTH_USER_MODEL),
        ),
    ]
