# Generated by Django 4.0.6 on 2022-08-29 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_requestrefundbankinfo_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestRefundBankInfo',
        ),
    ]
