# Generated by Django 4.0.6 on 2022-08-29 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_fundaccout_make_refund'),
        ('order', '0025_delete_requestrefundbankinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundItem',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fund_accounts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_items', to='account.fundaccout')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_items', to='order.orderitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
