# Generated by Django 4.0.6 on 2022-08-30 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0027_rename_refunditem_requestrefunditem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestrefunditem',
            options={'verbose_name_plural': 'Request Refund Items'},
        ),
        migrations.AddField(
            model_name='requestrefunditem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refund_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
