# Generated by Django 4.0.6 on 2022-08-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_alter_requestrefunditem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestrefunditem',
            name='recieved_product',
            field=models.BooleanField(default=False),
        ),
    ]
