# Generated by Django 4.0.6 on 2022-08-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0030_remove_requestrefunditem_recieved_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('razorpay_payout_id', models.CharField(max_length=64)),
                ('fund_account_id', models.CharField(max_length=64)),
                ('amount', models.CharField(max_length=64)),
                ('currency', models.CharField(max_length=3)),
                ('fees', models.CharField(max_length=64)),
                ('tax', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=64)),
                ('purpose', models.CharField(max_length=64)),
                ('mode', models.CharField(max_length=64)),
                ('reference_id', models.CharField(max_length=64)),
                ('merchant_id', models.CharField(max_length=64)),
                ('source', models.CharField(blank=True, max_length=64, null=True)),
                ('reason', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Payouts',
                'ordering': ('-id',),
            },
        ),
    ]
