# Generated by Django 4.0.6 on 2022-08-31 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0031_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payout', to='order.order'),
        ),
        migrations.AddField(
            model_name='payout',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payout', to='order.orderitem'),
        ),
        migrations.AddField(
            model_name='payout',
            name='utr',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
