# Generated by Django 4.0.6 on 2022-08-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0033_alter_payout_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='amount',
            field=models.PositiveBigIntegerField(),
        ),
    ]
